[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python -m spacy download de_core_news_sm"

[deploy]
startCommand = "python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
timeout = 10
interval = 30

